### ISSUE TITLE
【bug】使用pyinstaller打包后再执行报错

### ISSUE THREAD

**Issue by ellieot** [QPT-Family/QGUI#11]
[Errno 2] No such file or directory: 'xxxxx\\ttkbootstrap\\themes.json' 
[15164] Failed to execute script 'gui' due to unhandled exception!

Traceback (most recent call last):
  File "gui.py", line 484, in <module>
  File "qgui\factory.py", line 50, in __init__
  File "ttkbootstrap\__init__.py", line 80, in __init__
  File "ttkbootstrap\__init__.py", line 100, in _load_themes
  File "importlib\resources.py", line 169, in read_text
  File "importlib\resources.py", line 125, in open_text
  File "PyInstaller\loader\pyimod02_importers.py", line 539, in open_resource
  File "pathlib.py", line 1208, in open
  File "pathlib.py", line 1063, in _opener

**Comment by GT-ZhangAcer** [comment]
请issue至pyinstaller或ttkbootstrap


原因：
1. pyinstaller非Python官方或QPT-Family推荐打包工具，QGUI没有理由为非官方的打包工具做适配，这些工具数量众多，且该报错是pyinstaller对ttkbootstrap支持有问题而出现的，ttkbootstrap为Python官方推荐的tkinter所推荐的第三方库，理应pyinstaller对其适配。
2. ttkbootstrap与pyinstaller的矛盾不应该由QGUI解决，如果解决只能删去ttkbootstrap或ttkbootstrap官方处理，然而这并不是QGUI能接受的事情。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月13日(周六) 中午1:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [QPT-Family/QGUI] 【bug】使用pyinstaller打包后再执行报错 (Issue #11)




 
[Errno 2] No such file or directory: 'xxxxx\ttkbootstrap\themes.json'
 [15164] Failed to execute script 'gui' due to unhandled exception!
 
Traceback (most recent call last):
 File "gui.py", line 484, in 
 File "qgui\factory.py", line 50, in init
 File "ttkbootstrap_init_.py", line 80, in init
 File "ttkbootstrap_init_.py", line 100, in _load_themes
 File "importlib\resources.py", line 169, in read_text
 File "importlib\resources.py", line 125, in open_text
 File "PyInstaller\loader\pyimod02_importers.py", line 539, in open_resource
 File "pathlib.py", line 1208, in open
 File "pathlib.py", line 1063, in _opener

**Comment by ellieot** [comment]
查阅ttkbootstrap之后发现解决办法了，这里给后来人提醒，只需要添加参数 --collect-all 即可
`pyinstaller yourprogram.py --collect-all ttkbootstrap`
