### ISSUE TITLE
跑readme的demo，提示未获取默认主题

### ISSUE THREAD

**Issue by livingbody** [QPT-Family/QGUI#3]
如题：跑readme的demo，提示未获取默认主题

`C:\Users\livingbody\miniconda3\envs\p2\python.exe C:/Users/livingbody/PycharmProjects/qguitest/main.py
Traceback (most recent call last):
  File "C:/Users/livingbody/PycharmProjects/qguitest/main.py", line 20, in <module>
    main_gui = CreateQGUI(title="一个新应用")
  File "f:\qgui\qgui\factory.py", line 52, in __init__
    self.root.style = Style(**QStyle.default)
  File "C:\Users\livingbody\miniconda3\envs\p2\lib\site-packages\ttkbootstrap\__init__.py", line 81, in __init__
    self._load_themes(themes_file)
  File "C:\Users\livingbody\miniconda3\envs\p2\lib\site-packages\ttkbootstrap\__init__.py", line 119, in _load_themes
    themetype=settings['type'],
TypeError: list indices must be integers or slices, not str

Process finished with exit code 1
`

**Comment by GT-ZhangAcer** [comment]
#4 感谢PR
