### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'themes_file'

### ISSUE THREAD

**Issue by Freddd13** [QPT-Family/QGUI#6]
Traceback (most recent call last):
  File "e:\music_tools\sep_gui\gui.py", line 12, in <module>
    main_gui = CreateQGUI(title="一个新应用")
  File "C:\software\miniconda3\envs\music\lib\site-packages\qgui-0.5-py3.7.egg\qgui\factory.py", line 52, in __init__
    self.root.style = Style(**QStyle.default)
TypeError: __new__() got an unexpected keyword argument 'themes_file'

**Comment by Freddd13** [comment]
环境miniconda python=3.7.11

**Comment by GT-ZhangAcer** [comment]
#4 这位老哥已经修复了，刚刚发布于0.6~
